### ISSUE TITLE
Using Radial and Fisheye Camera Calibration

### ISSUE THREAD

**Issue by pateljayam** [youkely/InfrasCal#10]
Hello @youkely 

Is it possible to run the calibration with a set of camera that include both RADIAL and FISHEYE modes?

```
 ./build/bin/infrastr_calib --camera-count 5 \
 --output ./data/demo/results \
 --map ./data/demo/map \
 --database ./data/demo/map/database.db \
 --input ./data/demo/ \
 --vocab ./data/vocabulary/sift128.bin \
 -v --camera-model pinhole-radtan --save
```

The above command given in the dataset shows that it can run of a dataset if all the camera are either RADIAL or FISHEYE. Is it possible to run the command for a dataset that contains both radial and fisheye?

Looking forward to your reply.

Regards
PJ

**Comment by pateljayam** [comment]
Also, my dataset includes a camera rig that has various camera spaced at different positions. 
For example, there are two cameras facing front and two cameras facing the sides, and there is distance between each one of them is around 1.5 meters.

**Comment by youkely** [comment]
Currently the method does not support multiple models. You may need to modify the codes in order to make it work.
The cameras placing around is not a problem for this method. We had tests with RobotSeason datasets with cameras around 1 meters away from each and pointing to different directions. You can checkout it in the paper.

**Comment by pateljayam** [comment]
Perfect. I will try doing so.

Thank you. I really appreciate your help.
