### ISSUE TITLE
Why do you need 3d coordinate values that match the SIFT feature points？  this is hard to get in practice.

### ISSUE THREAD

**Issue by wuyuanmm** [youkely/InfrasCal#2]
this is a very good job , thanks to publish it !  I read this codes,  It may be that there is a problem with my understanding.I think the only regret is that this method requires 3d coordinate values that match the SIFT features, which limits the practical application of this method. how to improve this ? I'm looking forward to the replay, thanks !

**Comment by tsattler** [comment]
The code calibrates the cameras based on 2D-3D matches between images and 3D points in a map. As such, it requires 3D coordinates for the matching SIFT features, otherwise this type of calibration approach cannot work.

You can find more details in the paper describing the system: https://www.ecva.net/papers/eccv_2020/papers_ECCV/html/2550_ECCV_2020_paper.php

**Comment by wuyuanmm** [comment]
I appreciate your replay, I get it, thanks!
